Restrict query of iface attrs in linuxbridge agent
sapcc/neutron pull request #20
Opened 2021-12-08 17:42 UTC by sebageek

For a linuxbridge-agent the startup performance gets worse the more
networks are scheduled onto the agent. One factor in this is that
parsing and transporting all netlink attributes for all interfaces takes
a long time. This makes functions like get_link_devices() pretty slow.
The more interfaces there are the slower it gets.

To prevent this an attribute filter is introduced to get_link_devices()
and to make_serializable(). Only specified attributes are serialized for
transport from each interface. As attributes can also be nested, this
can save up a lot of processing time, especially when only the interface
name is needed by the caller.

get_devices_info() now allows interface attributes to be restricted to a
subset as well. The function will determine which netlink attributes
need to be requested.

Co-authored-by: Johannes Kulik <johannes.kulik@sap.com>

2021-12-09 15:11 UTC, joker-at-work requested changes

2021-12-09 15:11 UTC, joker-at-work commented on neutron/agent/linux/ip_lib.py
> +        'parent_index': ['IFLA_LINKINFO'],
This needs to include `INFA_LINK`, too. Otherwise, we don't enter the `if`.

2021-12-09 15:11 UTC, joker-at-work commented on neutron/agent/linux/ip_lib.py
> +                     'IFLA_VXLAN_ID'],
We might want to consider adding `parent_name`, which needs `['IFLA_LINKINFO', 'IFLA_IFNAME']`. Not sure about the 3 missing `vxlan_*`. We should probably support them, too, just for completeness sake.

2021-12-15 17:41 UTC, sebageek commented on neutron/agent/linux/ip_lib.py
> +                             'IFLA_VXLAN_LINK'],
Hmm really feels somehwat clunky solving it this way.

2022-01-06 13:46 UTC, joker-at-work commented on neutron/agent/linux/ip_lib.py
> +                             'IFLA_VXLAN_LINK'],
You changes don't work, I think. As long as `vxlan_link_index` was requested, we will enter the `elif` and thus assume `name` to exist. Therefore, both `vxlan_link_name` and `vxlan_link_index` need the same attributes *AND* need to include `IFLA_NAME` in them, too.

2022-01-06 15:54 UTC, joker-at-work approved these changes

2022-01-07 14:25 UTC, merged