Fix PTR logic for updates
sapcc/neutron pull request #67
Opened 2024-07-18 15:00 UTC by galkindmitrii

Currently Neutron-Designate integration will fail if target PTR record already exists. This can happen if the FIP was in use before or if PTR was created manually.

Instead of failing with error we want to update existing PTR in such case.

2024-07-22 07:45 UTC, mutax approved these changes
Personally I would love if there is a way to have a INSERT or UPDATE semantic in one call, but I don't know if the api allows that or the update call would do that, so one could use the update call in the first place.

2024-07-22 12:12 UTC, mbrowny approved these changes

2024-07-26 09:18 UTC, mutax requested changes
here the outer designate_admin is being overwritten with the edit_managed option, but designate_admin is used in the next iteration again, now with that option set.

2024-07-26 09:18 UTC, mutax commented on neutron/services/externaldns/drivers/designate/driver.py
> +                designate, designate_admin = get_clients(context,
here the outer designate_admin is being overwritten with the edit_managed option, but designate_admin is used in the next iteration again, now with that option set.

2024-07-26 09:23 UTC, galkindmitrii commented on neutron/services/externaldns/drivers/designate/driver.py
> +                designate, designate_admin = get_clients(context,
> here the outer designate and designate_admin are being overwritten with the edit_managed option, but designate_admin is used in the next iteration again, now with that option set.

No, that's not how try - except logic works. The block under `except d_exc.NotFound `is not executed if `d_exc.Conflict` was raised.

2024-07-26 10:11 UTC, mutax commented on neutron/services/externaldns/drivers/designate/driver.py
> +                designate, designate_admin = get_clients(context,
but when handling the next record the body of the loop will use it

2024-07-26 10:33 UTC, mutax approved these changes

2024-08-01 14:33 UTC, rhalina submitted a review, later dismissed
Florian already approved it from the designate team side

2024-08-07 13:46 UTC, galkindmitrii commented
rebased and updated for checks to pass.

2024-08-08 07:46 UTC, mutax approved these changes

2024-08-08 07:51 UTC, rhalina approved these changes

2024-08-08 07:52 UTC, merged